const translations = {
  de: {
    navStart: "Start",
    navMaterialien: "Materialien",
    navSeminar: "Seminar",
    navMitmachen: "Mitmachen",

    heroTitle: "KIVIMA: KI-gestützte Visualisierungen im Mathematikunterricht",
    heroText: "Willkommen auf der Projektseite von <strong>KIVIMA</strong>. Hier sammeln wir Materialien, Informationen und Ergebnisse aus dem Seminar, in dem Lehramtsstudierende interaktive Lernumgebungen entwickeln und sie im <strong>teutolab mathematik</strong> mit Schüler*innen erproben.",
    heroButton: "Zu den Materialien",
    processTitle: "KIVIMA-Entwicklungsprozess",
    processText: "So läuft KIVIMA ab: vom Seminarstart über die Erprobung bis zur Veröffentlichung der Materialien.",
    processCaption: "Visualisierung des Entwicklungsprozesses aus den Projectinfos.",
    aboutTitle: "Was ist KIVIMA?",
    aboutText: "KIVIMA ist ein vom Qualitätsfonds für Lehre gefördertes Seminarkonzept an der Universität Bielefeld. Lehramtsstudierende der Mathematik entwickeln dabei mit Hilfe von KI-Werkzeugen innovative Unterrichtsmaterialien und dynamische Visualisierungen. Diese werden nicht nur theoretisch konzipiert, sondern im teutolab mathematik praxisnah mit Schülerinnen und Schülern erprobt und reflektiert.",
    quickTitle: "Schnellzugriff",
    card1Title: "Materialsammlung",
    card1Text: "Alle bisher verfügbaren Dokumente, Handreichungen und Downloads.",
    card1Button: "Materialien öffnen",
    card2Title: "Seminarphasen",
    card2Text: "Einblick in Entwicklung, Erprobung im Teutolab und Nachbereitung.",
    card2Button: "Seminar ansehen",
    card3Title: "Teilnahme & Kontakt",
    card3Text: "Informationen für Schulen und Interessierte sowie Kontaktmöglichkeiten.",
    card3Button: "Mehr erfahren",
    partnerTitle: "Partner & Förderung",
    fundingNote: "Gefördert durch den<br /><a href=\"https://www.uni-bielefeld.de/einrichtungen/zll/hdle/qualitaetsfonds/\" target=\"_blank\" rel=\"noopener noreferrer\">Qualitätsfonds für Lehre</a>.",
    footerText: "<strong>KIVIMA</strong> – Projektseite im Kontext des <strong>teutolab mathematik</strong> der Universität Bielefeld.",

    matHeroTitle: "Materialien",
    matHeroText: "Auf dieser Unterseite stellen wir aktuelle Dokumente aus dem KIVIMA-Projekt bereit.",
    matSectionFig: "Figurierte Zahlen",
    matDocTitle: "Arbeitsblätter (DOCX)",
    matPart1: "Teil 1: Figurierte Zahlen",
    matPart2: "Teil 2: Pythagoräische Tripel",
    matPart3: "Teil 3: Summe zweier Quadrate",
    matPart4: "Teil 4: Beweis durch Windmühlen",
    matDigitalTitle: "Digitale Lerneinheiten (HTML)",
    matLearn1: "Lernumgebung: Quadratzahlen",
    matLearn2: "Lernumgebung: Punktmuster und Formeln",
    matPlanTitle: "Geplante Erweiterungen",
    matPlan1: "Interaktive Visualisierungen aus dem Seminar (HTML/JavaScript)",
    matPlan2: "Didaktische Kommentare zu den Materialien",
    matPlan3: "Prompt-Dokumentationen zur KI-gestützten Erstellung",
    matPlan4: "Verlinkung veröffentlichter OER-Versionen (z. B. ORCA.nrw)",
    matFooter: "KIVIMA – Materialien aus dem Seminar und dem teutolab mathematik.",

    semHeroTitle: "Ablauf des Seminars",
    semHeroText: "Das Seminar ist in drei aufeinander bezogene Phasen gegliedert.",
    semPhase1Title: "1) Entwicklungsphase",
    semPhase1Text: "Einführung in KI-Werkzeuge (z. B. BIKI), Entwicklung von Visualisierungsideen und technischer Aufbau erster Prototypen.",
    semBruchmemoryTitle: "Varianten des Bruchmemory",
    semPhase2Title: "2) Erprobung im teutolab mathematik",
    semPhase2Text: "Durchführung von Stationen mit Schüler*innen der Klassen 9/10, Beobachtung und direkte Reflexion in den Studierendenteams.",
    semPhase3Title: "3) Nachbereitung & OER",
    semPhase3Text: "Überarbeitung der Materialien inklusive didaktischer Kommentare und Veröffentlichung ausgewählter Ergebnisse als offen zugängliche Ressourcen.",
    semFooter: "KIVIMA – Praxisorientierte Lerngelegenheiten im Lehramtsstudium Mathematik.",

    mitHeroTitle: "Mitmachen im Projekt",
    mitHeroText: "Für interessierte Schulen, Lehrkräfte, Studierende und Projektpartner*innen.",
    mitInterestTitle: "Interesse an einer Teilnahme?",
    mitInterestText: "Sie möchten mit Ihrer Klasse am Teutolab-Angebot teilnehmen oder sich über das Seminar informieren? Dann melden Sie sich gerne beim Projektteam.",
    mitContactText: "Kontakt: <a href=\"mailto:vkatter@uni-bielefeld.de\">vkatter@uni-bielefeld.de</a>",
    mitWhoTitle: "Wer wir sind",
    mitValRole: "Postdoc am Institut für Didaktik der Mathematik.",
    mitValFocus: "<strong>Schwerpunkte:</strong> KI im Mathematikunterricht, Trigonometrie, Grundvorstellungen, Lehrerbildung",
    mitValMail: "<strong>E-Mail:</strong> <a href=\"mailto:vkatter@uni-bielefeld.de\">vkatter@uni-bielefeld.de</a>",
    mitUniPage: "Uni-Seite",
    mitHomePage: "Homepage",
    mitNicRole: "Postdoc am Institut für Didaktik der Mathematik.",
    mitNicFocus: "<strong>Schwerpunkt:</strong> Grundvorstellung der Exponentialfunktion",
    mitNicMail: "<strong>E-Mail:</strong> <a href=\"mailto:nicolas.alarcon@uni-bielefeld.de\">nicolas.alarcon@uni-bielefeld.de</a>",
    mitAudienceTitle: "Für wen ist die Seite gedacht?",
    mitAudience1: "Lehrkräfte und Schulen der Sekundarstufe I",
    mitAudience2: "Lehramtsstudierende im Fach Mathematik",
    mitAudience3: "Interessierte an KI-gestützter Materialentwicklung",
    mitFooter: "KIVIMA in Kooperation mit dem teutolab mathematik."
  },
  es: {
    navStart: "Inicio",
    navMaterialien: "Materiales",
    navSeminar: "Seminario",
    navMitmachen: "Participar",

    heroTitle: "KIVIMA: Visualizaciones con IA en la enseñanza de matemáticas",
    heroText: "Bienvenidos a la página del proyecto <strong>KIVIMA</strong>. Aquí reunimos materiales, información y resultados del seminario en el que estudiantes de profesorado desarrollan entornos de aprendizaje interactivos y los prueban con alumnado en el <strong>teutolab mathematik</strong>.",
    heroButton: "Ir a materiales",
    processTitle: "Proceso de desarrollo de KIVIMA",
    processText: "Así funciona KIVIMA: desde el inicio del seminario y la fase de prueba hasta la publicación de los materiales.",
    processCaption: "Visualización del proceso de desarrollo incluida en la información del proyecto.",
    aboutTitle: "¿Qué es KIVIMA?",
    aboutText: "KIVIMA es un concepto de seminario financiado por el Fondo de Calidad para la Enseñanza de la Universidad de Bielefeld. Estudiantes de profesorado de matemáticas desarrollan materiales didácticos innovadores y visualizaciones dinámicas con ayuda de herramientas de IA. Estos materiales no solo se diseñan teóricamente, sino que también se prueban y reflexionan en la práctica en teutolab mathematik junto con escolares.",
    quickTitle: "Acceso rápido",
    card1Title: "Colección de materiales",
    card1Text: "Todos los documentos, guías y descargas disponibles hasta ahora.",
    card1Button: "Abrir materiales",
    card2Title: "Fases del seminario",
    card2Text: "Panorama de desarrollo, prueba en teutolab y seguimiento.",
    card2Button: "Ver seminario",
    card3Title: "Participación y contacto",
    card3Text: "Información para centros educativos, personas interesadas y vías de contacto.",
    card3Button: "Más información",
    partnerTitle: "Socios y financiación",
    fundingNote: "Financiado por el<br /><a href=\"https://www.uni-bielefeld.de/einrichtungen/zll/hdle/qualitaetsfonds/\" target=\"_blank\" rel=\"noopener noreferrer\">Fondo de Calidad para la Enseñanza</a>.",
    footerText: "<strong>KIVIMA</strong> – Página del proyecto en el contexto de <strong>teutolab mathematik</strong> de la Universidad de Bielefeld.",

    matHeroTitle: "Materiales",
    matHeroText: "En esta subpágina ofrecemos documentos actuales del proyecto KIVIMA.",
    matSectionFig: "Números figurados",
    matDocTitle: "Hojas de trabajo (DOCX)",
    matPart1: "Parte 1: Números figurados",
    matPart2: "Parte 2: Tripletas pitagóricas",
    matPart3: "Parte 3: Suma de dos cuadrados",
    matPart4: "Parte 4: Demostración con molinos",
    matDigitalTitle: "Unidades digitales de aprendizaje (HTML)",
    matLearn1: "Entorno de aprendizaje: números cuadrados",
    matLearn2: "Entorno de aprendizaje: patrones de puntos y fórmulas",
    matPlanTitle: "Ampliaciones previstas",
    matPlan1: "Visualizaciones interactivas del seminario (HTML/JavaScript)",
    matPlan2: "Comentarios didácticos sobre los materiales",
    matPlan3: "Documentación de prompts para creación asistida por IA",
    matPlan4: "Enlaces a versiones OER publicadas (p. ej., ORCA.nrw)",
    matFooter: "KIVIMA – Materiales del seminario y de teutolab mathematik.",

    semHeroTitle: "Estructura del seminario",
    semHeroText: "El seminario se organiza en tres fases relacionadas entre sí.",
    semPhase1Title: "1) Fase de desarrollo",
    semPhase1Text: "Introducción a herramientas de IA (p. ej., BIKI), desarrollo de ideas de visualización y construcción técnica de primeros prototipos.",
    semBruchmemoryTitle: "Variantes del Bruchmemory",
    semPhase2Title: "2) Prueba en teutolab mathematik",
    semPhase2Text: "Realización de estaciones con alumnado de 9.º/10.º curso, observación y reflexión directa en los equipos de estudiantes.",
    semPhase3Title: "3) Revisión y OER",
    semPhase3Text: "Revisión de materiales incluyendo comentarios didácticos y publicación de resultados seleccionados como recursos de acceso abierto.",
    semFooter: "KIVIMA – Oportunidades de aprendizaje orientadas a la práctica en la formación docente de matemáticas.",

    mitHeroTitle: "Participar en el proyecto",
    mitHeroText: "Para centros educativos, profesorado, estudiantes y socios del proyecto interesados.",
    mitInterestTitle: "¿Interés en participar?",
    mitInterestText: "¿Desea participar con su clase en la oferta de teutolab o informarse sobre el seminario? Entonces póngase en contacto con el equipo del proyecto.",
    mitContactText: "Contacto: <a href=\"mailto:vkatter@uni-bielefeld.de\">vkatter@uni-bielefeld.de</a>",
    mitWhoTitle: "Quiénes somos",
    mitValRole: "Investigador posdoctoral en el Instituto de Didáctica de las Matemáticas.",
    mitValFocus: "<strong>Áreas:</strong> IA en educación matemática, trigonometría, representaciones conceptuales, formación docente",
    mitValMail: "<strong>Correo electrónico:</strong> <a href=\"mailto:vkatter@uni-bielefeld.de\">vkatter@uni-bielefeld.de</a>",
    mitUniPage: "Página universitaria",
    mitHomePage: "Página personal",
    mitNicRole: "Investigador posdoctoral en el Instituto de Didáctica de las Matemáticas.",
    mitNicFocus: "<strong>Área:</strong> representación conceptual de la función exponencial",
    mitNicMail: "<strong>Correo electrónico:</strong> <a href=\"mailto:nicolas.alarcon@uni-bielefeld.de\">nicolas.alarcon@uni-bielefeld.de</a>",
    mitAudienceTitle: "¿Para quién es esta página?",
    mitAudience1: "Docentes y centros de secundaria I",
    mitAudience2: "Estudiantes de profesorado de matemáticas",
    mitAudience3: "Personas interesadas en la creación de materiales asistida por IA",
    mitFooter: "KIVIMA en cooperación con teutolab mathematik."
  },
  en: {
    navStart: "Home",
    navMaterialien: "Materials",
    navSeminar: "Seminar",
    navMitmachen: "Get Involved",

    heroTitle: "KIVIMA: AI-supported visualizations in mathematics education",
    heroText: "Welcome to the <strong>KIVIMA</strong> project page. Here we collect materials, information, and outcomes from the seminar in which student teachers develop interactive learning environments and test them with pupils in the <strong>teutolab mathematik</strong>.",
    heroButton: "Go to materials",
    processTitle: "KIVIMA Development Process",
    processText: "This is how KIVIMA works: from seminar kick-off and classroom testing to publishing the materials.",
    processCaption: "Visualization of the development process from the project information.",
    aboutTitle: "What is KIVIMA?",
    aboutText: "KIVIMA is a seminar concept at Bielefeld University funded by the Teaching Quality Fund. Mathematics student teachers develop innovative teaching materials and dynamic visualizations with AI tools. These materials are not only designed theoretically but are also tested and reflected on in practice with school students at teutolab mathematik.",
    quickTitle: "Quick access",
    card1Title: "Material collection",
    card1Text: "All documents, handouts, and downloads currently available.",
    card1Button: "Open materials",
    card2Title: "Seminar phases",
    card2Text: "Insights into development, testing at teutolab, and follow-up.",
    card2Button: "View seminar",
    card3Title: "Participation & contact",
    card3Text: "Information for schools, interested parties, and contact options.",
    card3Button: "Learn more",
    partnerTitle: "Partners & funding",
    fundingNote: "Funded by the<br /><a href=\"https://www.uni-bielefeld.de/einrichtungen/zll/hdle/qualitaetsfonds/\" target=\"_blank\" rel=\"noopener noreferrer\">Teaching Quality Fund</a>.",
    footerText: "<strong>KIVIMA</strong> – Project page in the context of <strong>teutolab mathematik</strong> at Bielefeld University.",

    matHeroTitle: "Materials",
    matHeroText: "On this subpage we provide current documents from the KIVIMA project.",
    matSectionFig: "Figurate numbers",
    matDocTitle: "Worksheets (DOCX)",
    matPart1: "Part 1: Figurate numbers",
    matPart2: "Part 2: Pythagorean triples",
    matPart3: "Part 3: Sum of two squares",
    matPart4: "Part 4: Proof by windmills",
    matDigitalTitle: "Digital learning units (HTML)",
    matLearn1: "Learning environment: square numbers",
    matLearn2: "Learning environment: dot patterns and formulas",
    matPlanTitle: "Planned extensions",
    matPlan1: "Interactive visualizations from the seminar (HTML/JavaScript)",
    matPlan2: "Didactic commentary on the materials",
    matPlan3: "Prompt documentation for AI-supported creation",
    matPlan4: "Links to published OER versions (e.g., ORCA.nrw)",
    matFooter: "KIVIMA – Materials from the seminar and teutolab mathematik.",

    semHeroTitle: "Seminar structure",
    semHeroText: "The seminar is divided into three interrelated phases.",
    semPhase1Title: "1) Development phase",
    semPhase1Text: "Introduction to AI tools (e.g., BIKI), development of visualization ideas, and technical construction of initial prototypes.",
    semBruchmemoryTitle: "Bruchmemory variants",
    semPhase2Title: "2) Testing at teutolab mathematik",
    semPhase2Text: "Running stations with students in grades 9/10, observation, and direct reflection in the student teams.",
    semPhase3Title: "3) Revision & OER",
    semPhase3Text: "Revision of materials including didactic commentary and publication of selected results as openly accessible resources.",
    semFooter: "KIVIMA – Practice-oriented learning opportunities in mathematics teacher education.",

    mitHeroTitle: "Get involved in the project",
    mitHeroText: "For interested schools, teachers, university students, and project partners.",
    mitInterestTitle: "Interested in participating?",
    mitInterestText: "Would you like to participate with your class in the teutolab program or learn more about the seminar? Then please contact the project team.",
    mitContactText: "Contact: <a href=\"mailto:vkatter@uni-bielefeld.de\">vkatter@uni-bielefeld.de</a>",
    mitWhoTitle: "Who we are",
    mitValRole: "Postdoctoral researcher at the Institute for Didactics of Mathematics.",
    mitValFocus: "<strong>Focus areas:</strong> AI in mathematics education, trigonometry, conceptual understanding, teacher education",
    mitValMail: "<strong>Email:</strong> <a href=\"mailto:vkatter@uni-bielefeld.de\">vkatter@uni-bielefeld.de</a>",
    mitUniPage: "University page",
    mitHomePage: "Homepage",
    mitNicRole: "Postdoctoral researcher at the Institute for Didactics of Mathematics.",
    mitNicFocus: "<strong>Focus:</strong> conceptual understanding of the exponential function",
    mitNicMail: "<strong>Email:</strong> <a href=\"mailto:nicolas.alarcon@uni-bielefeld.de\">nicolas.alarcon@uni-bielefeld.de</a>",
    mitAudienceTitle: "Who is this site for?",
    mitAudience1: "Teachers and schools in lower secondary education",
    mitAudience2: "Mathematics student teachers",
    mitAudience3: "Anyone interested in AI-supported material development",
    mitFooter: "KIVIMA in cooperation with teutolab mathematik."
  }
};

const setLanguage = (lang) => {
  const selectedLanguage = translations[lang] ? lang : "de";
  document.documentElement.lang = selectedLanguage;
  localStorage.setItem("kivima-language", selectedLanguage);

  document.querySelectorAll("[data-i18n]").forEach((element) => {
    const key = element.dataset.i18n;
    if (translations[selectedLanguage][key]) {
      element.innerHTML = translations[selectedLanguage][key];
    }
  });

  document.querySelectorAll(".lang-btn").forEach((button) => {
    button.classList.toggle("active", button.dataset.lang === selectedLanguage);
  });
};

document.querySelectorAll(".lang-btn").forEach((button) => {
  button.addEventListener("click", () => setLanguage(button.dataset.lang));
});

const storedLanguage = localStorage.getItem("kivima-language") || "de";
setLanguage(storedLanguage);
